--   -------------------------------------------------- 
--   Generated by Enterprise Architect Version 8.0.858
--   Created On : 星期五, 24 三月, 2017
--   DBMS       : MySql
--   --------------------------------------------------


SET FOREIGN_KEY_CHECKS=0;


--  Drop Tables, Stored Procedures and Views

DROP TABLE IF EXISTS ac_permission;
DROP TABLE IF EXISTS ac_role;
DROP TABLE IF EXISTS ac_user;
DROP TABLE IF EXISTS sys_menu;

--  Create Tables

CREATE TABLE ac_user
(
  id BIGINT NOT NULL COMMENT '主键ID',
  loginId VARCHAR(16) NOT NULL COMMENT '用户登录帐号',
  roleId BIGINT NOT NULL COMMENT '角色表主键',
  createBy VARCHAR(16) COMMENT '创建者userId',
  createDate DATETIME COMMENT '创建日期',
  updateBy VARCHAR(16) COMMENT '更新者userId',
  updateDate DATETIME COMMENT '更新日期',
  PRIMARY KEY (id)
)  COMMENT='访问控制：用户表';

CREATE TABLE ac_role
(
  id BIGINT NOT NULL COMMENT '主键ID',
  roleName NVARCHAR(50) NOT NULL COMMENT '角色名称  ',
  description NVARCHAR(100) COMMENT '描述',
  createBy VARCHAR(16) COMMENT '创建者userId',
  createDate DATETIME COMMENT '创建日期',
  updateBy VARCHAR(16) COMMENT '更新者userId',
  updateDate DATETIME COMMENT '更新日期',
  PRIMARY KEY (id),
  UNIQUE union_unique(roleName)
)  COMMENT='访问控制：角色表';

CREATE TABLE ac_permission
(
	id BIGINT NOT NULL COMMENT '主键ID',
  roleId BIGINT NOT NULL COMMENT '角色表主键',
  resourceId BIGINT NOT NULL COMMENT '资源表主键',
  resourceName NVARCHAR(50) COMMENT '资源名称',
  resourceType VARCHAR(20) NOT NULL COMMENT '资源类型',
	createBy VARCHAR(16) COMMENT '创建者userId',
	createDate DATETIME COMMENT '创建日期',
	updateBy VARCHAR(16) COMMENT '更新者userId',
	updateDate DATETIME COMMENT '更新日期',
	PRIMARY KEY (id)
)  COMMENT='访问控制：权限表';

CREATE TABLE sys_menu
(
	id BIGINT NOT NULL,
	parentId BIGINT NOT NULL,
	menuName NVARCHAR(50) NOT NULL,
	menuAlias VARCHAR(50) NOT NULL,
	description NVARCHAR(100),
	createBy VARCHAR(50),
	createDate DATETIME,
	updateBy VARCHAR(50),
	updateDate DATETIME,
	UNIQUE UQ_sys_menu_id(id),
	UNIQUE UQ_sys_menu_menuAlias(menuAlias),
	UNIQUE UQ_sys_menu_menuName(menuName)
)  COMMENT='菜单表';

SET FOREIGN_KEY_CHECKS=1;